matrix:
- name: Markdown
  aspell:
    lang: en
    ignore-case: true
  dictionary:
    wordlists:
    - config/.custom-dictionary.txt
    encoding: utf-8
  pipeline:
  - pyspelling.filters.markdown:
      ignores:
      - code
  - pyspelling.filters.html:
      comments: false
      ignores:
      - code
      - pre
  sources:
  - 'docs/*.md'
  default_encoding: utf-8
